-- ============================================================================
-- db/h2/schema.sql
-- Esquema H2 local (Modo Servidor TCP) do modelo real de curvas de mercado,
-- transcrito de fotos de tela do script original (fonte: sistema com
-- BloombergCurvaPrimr.java) — ver db/migration/V22__legado_schema_curvas_mercado.sql
-- para as ressalvas da transcricao. Cobre V22 (tabelas), V23 (sequence de
-- tBtrsCurvaPrimr) e V25 (indice de tBtrsCurvaPrimr).
-- ============================================================================

-- Usuarios de aplicacao
CREATE USER IF NOT EXISTS curve_processor_app PASSWORD 'CurveProcessorP0c!Local' ADMIN;
CREATE USER IF NOT EXISTS curve_api_app PASSWORD 'CurveApiP0c!Local' ADMIN;
CREATE USER IF NOT EXISTS curve_engine_app PASSWORD 'CurveEngineP0c!Local' ADMIN;
CREATE USER IF NOT EXISTS curve_orchestrator_app PASSWORD 'CurveOrchestratorP0c!Local' ADMIN;

-- 1. tCurvaMercd (V22) — catalogo de curvas
CREATE TABLE IF NOT EXISTS tCurvaMercd (
    cTickerIndcd VARCHAR(50) NOT NULL,
    cClasfInstt VARCHAR(50) NULL,
    cClassAtivo VARCHAR(50) NULL,
    cPprioDado VARCHAR(50) NULL,
    cConfgIdtfd INT NULL,
    cCurvaReft VARCHAR(50) NULL,
    cFamlInsttFincr VARCHAR(50) NULL,
    cIndxdAtivo VARCHAR(50) NULL,
    cMoedaNegoc VARCHAR(1024) NULL,
    cNormaDia CHAR(20) NULL,
    cPaisInstt CHAR(20) NULL,
    cSitReg CHAR(20) NULL,
    cTickerIdtfdUnic VARCHAR(50) NULL,
    cTpoCotac CHAR(30) NULL,
    cTpoJuro CHAR(20) NULL,
    cTpoVlr CHAR(30) NULL,
    cUsuarAtulz VARCHAR(100) NULL,
    cUsuarCalc VARCHAR(100) NULL,
    dCriacReg TIMESTAMP NULL,
    dBaseReft DATE NULL,
    dInicVgcia DATE NULL,
    dUltAtulz TIMESTAMP NULL,
    dValidAte DATE NULL,
    iPrvdrDados VARCHAR(1024) NULL,
    rAtivoIndcd VARCHAR(1024) NULL,
    vFatorMultiAtivo DECIMAL(28,12) NULL,
    CONSTRAINT pk_tcurvamercd PRIMARY KEY (cTickerIndcd)
);

-- 2. tConfgCurva (V22, V27) — motor de calculo/interpolador por curva
CREATE TABLE IF NOT EXISTS tConfgCurva (
    cldtfdConfg INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cTickerIndcd VARCHAR(50) NULL,
    cAtivoFincr BOOLEAN NULL,
    cRotnaCalc VARCHAR(1024) NULL,
    cPosCalc VARCHAR(1024) NULL,
    cPreCalc VARCHAR(1024) NULL,
    cLingSist VARCHAR(1024) NULL,
    cModDado VARCHAR(1024) NULL,
    cMotorCalc VARCHAR(1024) NULL,
    cPosMotorCalc VARCHAR(1024) NULL,
    cPreMotorCalc VARCHAR(1024) NULL,
    cTpoInstt VARCHAR(50) NULL,
    cVrsaoReg INT NULL,
    dInicVgcia DATE NULL,
    dValidAte DATE NULL,
    CONSTRAINT pk_tconfgcurva PRIMARY KEY (cldtfdConfg),
    CONSTRAINT fk_tconfgcurva_tcurvamercd FOREIGN KEY (cTickerIndcd) REFERENCES tCurvaMercd (cTickerIndcd)
);
CREATE INDEX IF NOT EXISTS ix_tconfgcurva_cticker ON tConfgCurva (cTickerIndcd);

-- 3. tBtrsCurvaPrimr (V22, V25) — vertices brutos das 5 curvas TS B3 (fonte: TaxaSwap.txt)
CREATE TABLE IF NOT EXISTS tBtrsCurvaPrimr (
    cldtfdUnic INT NOT NULL,
    cTickerIndcd VARCHAR(50) NOT NULL,
    cDiaCorri INT NULL,
    cDiaUtil INT NULL,
    dBaseReft DATE NULL,
    vFatorAcum DECIMAL(28,16) NULL,
    vPrecoTx DECIMAL(28,12) NULL,
    vFatorDia DECIMAL(28,16) NULL,
    CONSTRAINT pk_tbtrscurvaprimr PRIMARY KEY (cldtfdUnic),
    CONSTRAINT fk_tbtrscurvaprimr_tcurvamercd FOREIGN KEY (cTickerIndcd) REFERENCES tCurvaMercd (cTickerIndcd)
);
CREATE INDEX IF NOT EXISTS ix_tbtrscurvaprimr_cticker_dbasereft ON tBtrsCurvaPrimr (cTickerIndcd, dBaseReft);
CREATE SEQUENCE IF NOT EXISTS seq_tbtrscurvaprimr_cidtfdunic START WITH 1 INCREMENT BY 1;

-- 4. tDadoCurva (V22, V26) — vertices construidos pelo curve-engine
CREATE TABLE IF NOT EXISTS tDadoCurva (
    dBaseReft DATE NOT NULL,
    cTickerIndcd VARCHAR(50) NOT NULL,
    dVertcReft DATE NOT NULL,
    vPrecoTx DECIMAL(28,12) NULL,
    CONSTRAINT pk_tdadocurva PRIMARY KEY (dBaseReft, cTickerIndcd, dVertcReft),
    CONSTRAINT fk_tdadocurva_tcurvamercd FOREIGN KEY (cTickerIndcd) REFERENCES tCurvaMercd (cTickerIndcd)
);

-- 5. tCurvaData (V22, V26) — curva construida e interpolada, lida pelo curve-api
CREATE TABLE IF NOT EXISTS tCurvaData (
    dBaseReft DATE NOT NULL,
    cTickerIndcd VARCHAR(50) NOT NULL,
    dVertcReft DATE NOT NULL,
    vPrecoTx DECIMAL(28,12) NULL,
    CONSTRAINT pk_tcurvadata PRIMARY KEY (dBaseReft, cTickerIndcd, dVertcReft),
    CONSTRAINT fk_tcurvadata_tdadocurva FOREIGN KEY (dBaseReft, cTickerIndcd, dVertcReft) REFERENCES tDadoCurva (dBaseReft, cTickerIndcd, dVertcReft)
);

-- 6. tPrvdrDadoMercd (V22) — provedores de dado de mercado
CREATE TABLE IF NOT EXISTS tPrvdrDadoMercd (
    iPrvdrDados VARCHAR(1024) NOT NULL,
    cInfoProdt VARCHAR(1024) NULL,
    cProdt VARCHAR(1024) NULL,
    iCoplt VARCHAR(50) NULL,
    CONSTRAINT pk_tprvdrdadomercd PRIMARY KEY (iPrvdrDados)
);

-- 7. tCurvaPrvdr (V22)
CREATE TABLE IF NOT EXISTS tCurvaPrvdr (
    cldtfdUnic INT NOT NULL,
    cPriorCsumo INT NULL,
    cPrvdrMercd VARCHAR(50) NULL,
    cTickerIndcd VARCHAR(50) NOT NULL,
    cTickerPrvdr VARCHAR(1024) NULL,
    iPrvdrDados VARCHAR(1024) NULL,
    CONSTRAINT pk_tcurvaprvdr PRIMARY KEY (cldtfdUnic),
    CONSTRAINT fk_tcurvaprvdr_tcurvamercd FOREIGN KEY (cTickerIndcd) REFERENCES tCurvaMercd (cTickerIndcd),
    CONSTRAINT fk_tcurvaprvdr_tprvdrdadomercd FOREIGN KEY (iPrvdrDados) REFERENCES tPrvdrDadoMercd (iPrvdrDados)
);
CREATE INDEX IF NOT EXISTS ix_tcurvaprvdr_iprvdrdados ON tCurvaPrvdr (iPrvdrDados);

-- 8. tDadoVertcCurva (V22)
CREATE TABLE IF NOT EXISTS tDadoVertcCurva (
    dBaseReft DATE NOT NULL,
    cTickerIndcd VARCHAR(50) NOT NULL,
    dVertcReft DATE NOT NULL,
    cDiaUtil INT NULL,
    vFatorDia DECIMAL(28,16) NULL,
    vFatorAcum DECIMAL(28,16) NULL,
    cQtdDiaPer INT NULL,
    cQtdDiaReft INT NULL,
    vPrecoTx DECIMAL(28,12) NULL,
    CONSTRAINT pk_tdadovertccurva PRIMARY KEY (dBaseReft, cTickerIndcd, dVertcReft),
    CONSTRAINT fk_tdadovertccurva_tcurvamercd FOREIGN KEY (cTickerIndcd) REFERENCES tCurvaMercd (cTickerIndcd)
);

-- 9. tGradeTpo (V22)
CREATE TABLE IF NOT EXISTS tGradeTpo (
    cTpoInstt VARCHAR(50) NOT NULL,
    cCalcMotor VARCHAR(1024) NULL,
    dVrsaoMod DATE NULL,
    CONSTRAINT pk_tgradetpo PRIMARY KEY (cTpoInstt)
);

-- 10. tGradeVoltl (V22)
CREATE TABLE IF NOT EXISTS tGradeVoltl (
    cTickerPrvdr VARCHAR(1024) NOT NULL,
    cExpirCad BOOLEAN NULL,
    cSedolAtivo CHAR(30) NULL,
    dCriacReg TIMESTAMP NULL,
    dUltAtulz TIMESTAMP NULL,
    cTpoInstt VARCHAR(50) NOT NULL,
    cTickerBberg VARCHAR(50) NULL,
    iRegAtivo VARCHAR(1024) NULL,
    CONSTRAINT pk_tgradevoltl PRIMARY KEY (cTickerPrvdr),
    CONSTRAINT fk_tgradevoltl_tgradetpo FOREIGN KEY (cTpoInstt) REFERENCES tGradeTpo (cTpoInstt)
);
CREATE INDEX IF NOT EXISTS ix_tgradevoltl_ctpoinstt ON tGradeVoltl (cTpoInstt);

-- 11. tGradeMtrizData (V22)
CREATE TABLE IF NOT EXISTS tGradeMtrizData (
    cldtfdUnic INT NOT NULL,
    dBaseReft DATE NULL,
    cFormtArq VARCHAR(200) NULL,
    cModLyoutCarga CHAR(16) NULL,
    cTickerPrvdr VARCHAR(1024) NOT NULL,
    cTpoCotac CHAR(30) NULL,
    cVrsaoReg INT NULL,
    dCriacReg TIMESTAMP NULL,
    dUltAtulz TIMESTAMP NULL,
    CONSTRAINT pk_tgrademtrizdata PRIMARY KEY (cldtfdUnic),
    CONSTRAINT fk_tgrademtrizdata_tgradevoltl FOREIGN KEY (cTickerPrvdr) REFERENCES tGradeVoltl (cTickerPrvdr)
);

-- 12. tMtrizCurva (V22)
CREATE TABLE IF NOT EXISTS tMtrizCurva (
    cTickerIndcd VARCHAR(50) NOT NULL,
    dBaseReft DATE NOT NULL,
    cFormtArq VARCHAR(200) NULL,
    cModLyoutCarga CHAR(16) NULL,
    cTpoInstt VARCHAR(50) NULL,
    cVrsaoReg INT NULL,
    dCriacReg TIMESTAMP NULL,
    dUltAtulz TIMESTAMP NULL,
    CONSTRAINT pk_tmtrizcurva PRIMARY KEY (cTickerIndcd, dBaseReft),
    CONSTRAINT fk_tmtrizcurva_tcurvamercd FOREIGN KEY (cTickerIndcd) REFERENCES tCurvaMercd (cTickerIndcd)
);
CREATE INDEX IF NOT EXISTS ix_tmtrizcurva_cticker ON tMtrizCurva (cTickerIndcd);

-- 13. tAnbmaCurvaPrimr (V22)
CREATE TABLE IF NOT EXISTS tAnbmaCurvaPrimr (
    cldtfdUnic INT NOT NULL,
    cTickerIndcd VARCHAR(50) NOT NULL,
    dBaseReft DATE NULL,
    vPrecoTx DECIMAL(28,12) NULL,
    vVertcCurva DECIMAL(28,12) NULL,
    CONSTRAINT pk_tanbmacurvaprimr PRIMARY KEY (cldtfdUnic),
    CONSTRAINT fk_tanbmacurvaprimr_tcurvamercd FOREIGN KEY (cTickerIndcd) REFERENCES tCurvaMercd (cTickerIndcd)
);
CREATE INDEX IF NOT EXISTS ix_tanbmacurvaprimr_cticker ON tAnbmaCurvaPrimr (cTickerIndcd);

-- 14. tBbergCurvaPrimr (V22)
CREATE TABLE IF NOT EXISTS tBbergCurvaPrimr (
    cldtfdUnic INT NOT NULL,
    cTickerIndcd VARCHAR(50) NOT NULL,
    cDiaVcto INT NULL,
    cFormaLiqdc CHAR(20) NULL,
    cTickerBberg CHAR(20) NULL,
    dBaseReft DATE NULL,
    dLiqdcFincr DATE NULL,
    dVctoContr DATE NULL,
    dUltNegoc DATE NULL,
    vPrecoLiqdc DECIMAL(28,12) NULL,
    vPrecoMed DECIMAL(28,12) NULL,
    vPrecoUlt DECIMAL(28,12) NULL,
    CONSTRAINT pk_tbbergcurvaprimr PRIMARY KEY (cldtfdUnic),
    CONSTRAINT fk_tbbergcurvaprimr_tcurvamercd FOREIGN KEY (cTickerIndcd) REFERENCES tCurvaMercd (cTickerIndcd)
);
CREATE INDEX IF NOT EXISTS ix_tbbergcurvaprimr_cticker ON tBbergCurvaPrimr (cTickerIndcd);

-- 15. tCmeCurvaPrimr (V22)
CREATE TABLE IF NOT EXISTS tCmeCurvaPrimr (
    cldtfdUnic INT NOT NULL,
    cTickerIndcd VARCHAR(50) NOT NULL,
    cDsvioAjustCurva INT NULL,
    dBaseReft DATE NULL,
    vFatorDesc DECIMAL(28,12) NULL,
    CONSTRAINT pk_tcmecurvaprimr PRIMARY KEY (cldtfdUnic, cTickerIndcd),
    CONSTRAINT fk_tcmecurvaprimr_tcurvamercd FOREIGN KEY (cTickerIndcd) REFERENCES tCurvaMercd (cTickerIndcd)
);
CREATE INDEX IF NOT EXISTS ix_tcmecurvaprimr_cticker ON tCmeCurvaPrimr (cTickerIndcd);

-- 16. tLchCurvaPrimr (V22)
CREATE TABLE IF NOT EXISTS tLchCurvaPrimr (
    cldtfdUnic INT NOT NULL,
    cTickerIndcd VARCHAR(50) NOT NULL,
    cCurvaCompd INT NULL,
    cTpoInsttCurva VARCHAR(50) NULL,
    dBaseReft DATE NULL,
    dVctoContr DATE NULL,
    vAcumFator DECIMAL(28,16) NULL,
    vFatorDesc DECIMAL(28,12) NULL,
    vTxEquil DECIMAL(28,12) NULL,
    vTxZero DECIMAL(28,12) NULL,
    CONSTRAINT pk_tlchcurvaprimr PRIMARY KEY (cldtfdUnic),
    CONSTRAINT fk_tlchcurvaprimr_tcurvamercd FOREIGN KEY (cTickerIndcd) REFERENCES tCurvaMercd (cTickerIndcd)
);
CREATE INDEX IF NOT EXISTS ix_tlchcurvaprimr_cticker ON tLchCurvaPrimr (cTickerIndcd);

-- 17. tLsegCurvaPrimr (V22)
CREATE TABLE IF NOT EXISTS tLsegCurvaPrimr (
    cldtfdUnic INT NOT NULL,
    cTickerIndcd VARCHAR(50) NOT NULL,
    cDiaVcto INT NULL,
    cFormaLiqdc CHAR(20) NULL,
    dBaseReft DATE NULL,
    dVctoContr DATE NULL,
    dUltNegoc DATE NULL,
    vPrecoLiqdc DECIMAL(28,12) NULL,
    vPrecoMed DECIMAL(28,12) NULL,
    vPrecoUlt DECIMAL(28,12) NULL,
    CONSTRAINT pk_tlsegcurvaprimr PRIMARY KEY (cldtfdUnic),
    CONSTRAINT fk_tlsegcurvaprimr_tcurvamercd FOREIGN KEY (cTickerIndcd) REFERENCES tCurvaMercd (cTickerIndcd)
);
CREATE INDEX IF NOT EXISTS ix_tlsegcurvaprimr_cticker ON tLsegCurvaPrimr (cTickerIndcd);

-- 18. tTesouCurvaPrimr (V22)
CREATE TABLE IF NOT EXISTS tTesouCurvaPrimr (
    cldtfdUnic INT NOT NULL,
    dBaseReft DATE NULL,
    cNegocDay INT NULL,
    cQtdDiaPer INT NULL,
    cQtdDiaReft INT NULL,
    cTickerIndcd VARCHAR(50) NULL,
    vDiaFator DECIMAL(28,16) NULL,
    vFatorCalc DECIMAL(28,16) NULL,
    vPrecoTx DECIMAL(28,12) NULL,
    CONSTRAINT pk_ttesoucurvaprimr PRIMARY KEY (cldtfdUnic),
    CONSTRAINT fk_ttesoucurvaprimr_tcurvamercd FOREIGN KEY (cTickerIndcd) REFERENCES tCurvaMercd (cTickerIndcd)
);
CREATE INDEX IF NOT EXISTS ix_ttesoucurvaprimr_cticker ON tTesouCurvaPrimr (cTickerIndcd);

-- 19. tTrefaAgnda (V22) — agendamento de tarefas do sistema legado
CREATE TABLE IF NOT EXISTS tTrefaAgnda (
    cldtfdTrefa INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cAcaoOperSist VARCHAR(1024) NOT NULL,
    cRegraAgnda CHAR(15) NULL,
    cRegraIntvl CHAR(20) NULL,
    cSit CHAR(30) NULL,
    iParmTrefa VARCHAR(255) NULL,
    rTrefa VARCHAR(1024) NULL,
    CONSTRAINT pk_ttrefaagnda PRIMARY KEY (cldtfdTrefa)
);

-- 20. tParmTrefa (V22)
CREATE TABLE IF NOT EXISTS tParmTrefa (
    cldtfdParm INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cldtfdTrefa INT NOT NULL,
    cCategParmConfg VARCHAR(255) NULL,
    iParmTrefa VARCHAR(255) NULL,
    rParmTrefa VARCHAR(8000) NULL,
    CONSTRAINT pk_tparmtrefa PRIMARY KEY (cldtfdParm),
    CONSTRAINT fk_tparmtrefa_ttrefaagnda FOREIGN KEY (cldtfdTrefa) REFERENCES tTrefaAgnda (cldtfdTrefa)
);
CREATE INDEX IF NOT EXISTS ix_tparmtrefa_cldtfdtrefa ON tParmTrefa (cldtfdTrefa);

-- 21. tLogTrefa (V22)
CREATE TABLE IF NOT EXISTS tLogTrefa (
    cldtfdEntrd INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cldtfdTrefa INT NOT NULL,
    cSitExcuc INT NULL,
    dAtaCriac TIMESTAMP NOT NULL,
    rLogTrefa VARCHAR(8000) NULL,
    CONSTRAINT pk_tlogtrefa PRIMARY KEY (cldtfdEntrd),
    CONSTRAINT fk_tlogtrefa_ttrefaagnda FOREIGN KEY (cldtfdTrefa) REFERENCES tTrefaAgnda (cldtfdTrefa)
);
CREATE INDEX IF NOT EXISTS ix_tlogtrefa_cldtfdtrefa ON tLogTrefa (cldtfdTrefa);

-- 22. tParmTpoGrade (V22)
CREATE TABLE IF NOT EXISTS tParmTpoGrade (
    cldtfdUnic INT NOT NULL,
    cTpoParm VARCHAR(255) NULL,
    cParmConfg VARCHAR(8000) NULL,
    iParmConfg VARCHAR(50) NULL,
    cTpoInstt VARCHAR(50) NULL,
    CONSTRAINT pk_tparmtpograde PRIMARY KEY (cldtfdUnic),
    CONSTRAINT fk_tparmtpograde_tgradetpo FOREIGN KEY (cTpoInstt) REFERENCES tGradeTpo (cTpoInstt)
);
CREATE INDEX IF NOT EXISTS ix_tparmtpograde_ctpoinstt ON tParmTpoGrade (cTpoInstt);

-- 23. tParmConfgCurva (V22)
CREATE TABLE IF NOT EXISTS tParmConfgCurva (
    cldtfdConfg INT NOT NULL,
    cTpoInstt VARCHAR(50) NULL,
    iPrvdrDados VARCHAR(1024) NULL,
    vPrecoTx DECIMAL(28,12) NULL,
    cConfgIdtfd INT NULL,
    CONSTRAINT pk_tparmconfgcurva PRIMARY KEY (cldtfdConfg),
    CONSTRAINT fk_tparmconfgcurva_tconfgcurva FOREIGN KEY (cldtfdConfg) REFERENCES tConfgCurva (cldtfdConfg)
);
