spring:
  application:
    name: '@project.name@'
  config:
    import: "optional:configtree:/mnt/secrets-store/"
  lifecycle.timeout-per-shutdown-phase: "2s"

  datasource:
    url: ${DATABASE_URL:jdbc:sqlserver://localhost:1433;database=curvas;encrypt=false}
    username: ${DATABASE_USERNAME:}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        default_schema: dbo
    show-sql: ${JPA_SHOW_SQL:false}
    open-in-view: false

  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss
    default-property-inclusion: NON_NULL
    datatype.datetime.write-dates-as-timestamps: false

  threads:
    virtual:
      enabled: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    problemdetails:
      enabled: true

  cloud:
    compatibility-verifier:
      enabled: false
    openfeign:
      httpclient:
        connection-timeout: ${OPENFEIGN_HTTPCLIENT_CONNECTION_TIMEOUT:2000}
        max-connections: ${OPENFEIGN_HTTPCLIENT_MAX_CONNECTIONS:200}
        max-connections-per-route: ${OPENFEIGN_HTTPCLIENT_MAX_CONNECTIONS_PER_ROUTE:50}
        time-to-live: ${OPENFEIGN_TIME_TO_LIVE:900}
        time-to-live-unit: seconds
        hc5:
          connectionRequestTimeout: ${HC5_CONNECTION_REQUEST_TIMEOUT_POOL:3}
      lazy-attributes-resolution: true
      client:
        config:
          default:
            connectTimeout: ${OPENFEIGN_HTTPCLIENT_CONNECT_TIMEOUT:6000}
            readTimeout: ${OPENFEIGN_HTTPCLIENT_READ_TIMEOUT:6000}
            loggerLevel: ${OPENFEIGN_HTTPCLIENT_LOGGER_LEVEL:BASIC}
            dismiss404: false
            micrometer:
              enabled: true

server:
  port: ${SERVER_PORT:8080}
  shutdown: "immediate"
  tomcat:
    threads:
      max: ${SERVER_PARALELISM:200}

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health
    access:
      default: NONE
  endpoint:
    health:
      access: UNRESTRICTED
      show-components: "always"
      show-details: "never"
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState, ping
        readiness:
          include: readinessState, ping
  health:
    diskspace:
      enabled: false
  opentelemetry:
    resource-attributes:
      service.name: ${spring.application.name}
      service.instance.id: ${HOSTNAME:unknown}
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: w3c,b3,b3_multi
      produce: w3c

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    br.com.poc: ${LOG_LEVEL_BR_COM_POC:${LOG_LEVEL:INFO}}
    org.hibernate.type: WARN

springdoc:
  swagger-ui:
    tagsSorter: alpha
